# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93524929828a19905f3b419f4d639dac3977e48d94cc622a6980e7abc720e70ef95112f2879f7f1b63ea94bbd193dce4b7172caadc33c18e000d37a53a16112c

test:
  secret_key_base: b4c1b9a393cef769c3fe35a0f0e011374c2241430da01e691e3e7af9f55520a8e57db18c21d8da721cde1c6e23f445e24dcd33a5706d9bb299ba5982b0bd5259

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
